import { stocked } from "./stock";
import type { Product, SupplierQuote } from "./types";

function quote(
  productId: string,
  slug: string,
  input: Omit<SupplierQuote, "id">,
): SupplierQuote {
  return { id: `${productId}:${slug}`, ...input };
}

const catalogProducts: Product[] = [
  {
    id: "sheet-pan",
    sku: "LN-PAN-Q",
    name: "Quarter sheet pan with a wire rack",
    titleLead: "Quarter sheet pan and rack",
    category: "Pans",
    lane: "kitchen",
    occasion: "a weeknight after a shift",
    material: "Aluminum pan, stainless rack",
    size: "9 × 13 in",
    colorway: "Steel",
    swatch: "#c5c8ce",
    ceiling: 36,
    neededInDays: 10,
    box: "One quarter sheet and one fitted rack. No parchment.",
    useLine: "One pan, one rack, dinner done. The rack keeps the chicken out of the fat.",
    colorNote: "Bare aluminum. It will darken. That is use, not a defect.",
    hook: "You worked a line. Dinner at home should still be one pan.",
    searchPhrase: "quarter sheet pan rack weeknight dinner",
    keywords: ["sheet pan", "quarter sheet", "wire rack", "weeknight dinner", "line cook"],
    complements: "a bench scraper and a towel that can take heat",
    trend: {
      platform: "Posts",
      title: "Sheet-pan dinners after a double",
      signal: "Cooks are posting the one-pan meal they make when they get home, not a ten-step recipe.",
      evidence:
        "line cooks posting a quarter sheet, a rack, and whatever protein was on the way home. The useful object is the pan, not a gadget.",
    },
    mockups: [
      {
        title: "Pan and rack",
        direction: "Rack seated in the pan, empty, overhead. No styled food.",
        layout: "stack",
        src: "/art/mock-sheet-pan-1.png",
      },
      {
        title: "After service",
        direction: "Same pan with chicken and vegetables. Caption says it was a Tuesday.",
        layout: "line",
        src: "/art/mock-sheet-pan-2.png",
      },
      {
        title: "In the cabinet",
        direction: "Pan stored upright beside the organizer. No food.",
        layout: "pair",
        src: "/art/mock-sheet-pan-3.png",
      },
    ],
    suppliers: [
      quote("sheet-pan", "northwharf", {
        name: "Northwharf Goods",
        origin: "Elizabeth, NJ",
        speed: "us",
        unitCost: 11,
        inboundShipping: 0,
        packaging: 1.2,
        shipDaysMin: 2,
        shipDaysMax: 4,
        rating: 4.8,
        reviews: 640,
        moq: 1,
        returnWindowDays: 30,
        note: "In the NJ warehouse. The rack fits this pan, checked on the sample.",
      }),
      quote("sheet-pan", "harborkit", {
        name: "Harborkit",
        origin: "Los Angeles, CA",
        speed: "us",
        unitCost: 13.4,
        inboundShipping: 1.1,
        packaging: 1.1,
        shipDaysMin: 3,
        shipDaysMax: 5,
        rating: 4.7,
        reviews: 210,
        moq: 1,
        returnWindowDays: 30,
        note: "Same pan, West Coast. Use it if NJ is thin.",
      }),
      quote("sheet-pan", "paperlane", {
        name: "Paperlane Direct",
        origin: "Yiwu, China",
        speed: "import",
        unitCost: 6.2,
        inboundShipping: 4.4,
        packaging: 0.8,
        shipDaysMin: 16,
        shipDaysMax: 24,
        rating: 4.5,
        reviews: 900,
        moq: 8,
        returnWindowDays: 7,
        note: "Cheaper on paper. Three weeks, and the rack warps in the reviews.",
      }),
    ],
  },
  {
    id: "bench-scraper",
    sku: "LN-SCR-1",
    name: "Stainless bench scraper",
    titleLead: "Stainless bench scraper",
    category: "Prep",
    lane: "kitchen",
    occasion: "prep at home",
    material: "Stainless steel",
    size: "6 in blade",
    colorway: "Steel",
    swatch: "#d6d7dc",
    ceiling: 18,
    neededInDays: 12,
    box: "One scraper. No ruler marks, no silicone sleeve.",
    useLine: "Cut dough, lift chopped onion, scrape the board into the pan.",
    colorNote: "One piece of steel. The edge is blunt enough for a board and sharp enough to portion.",
    hook: "The tool you actually reach for is a scraper, not a gadget.",
    searchPhrase: "stainless bench scraper dough cutter",
    keywords: ["bench scraper", "dough cutter", "prep tool", "kitchen utensil"],
    complements: "a wood board and the quarter sheet",
    trend: {
      platform: "TikTok",
      title: "Bench scraper, not a 12-piece set",
      signal: "Prep clips keep cutting to one steel scraper. The sets are the thing people regret.",
      evidence:
        "TikTok prep videos this month use a single bench scraper for dough and veg. The supplier book has a US blank, not a 20-piece import set.",
    },
    mockups: [
      {
        title: "On the board",
        direction: "Scraper flat on a wood board with a pile of diced onion.",
        layout: "stack",
        src: "/art/mock-bench-scraper-1.png",
      },
      {
        title: "Edge",
        direction: "Crop on the steel edge so it does not look like a toy.",
        layout: "line",
        src: "/art/mock-bench-scraper-2.png",
      },
      {
        title: "In the crock",
        direction: "Standing with one spoon. No food.",
        layout: "pair",
        src: "/art/mock-bench-scraper-3.png",
      },
    ],
    suppliers: [
      quote("bench-scraper", "northwharf", {
        name: "Northwharf Goods",
        origin: "Elizabeth, NJ",
        speed: "us",
        unitCost: 3.4,
        inboundShipping: 0,
        packaging: 0.35,
        shipDaysMin: 2,
        shipDaysMax: 4,
        rating: 4.8,
        reviews: 410,
        moq: 1,
        returnWindowDays: 30,
        note: "Stiff enough. The sample did not flex on a cold dough.",
      }),
      quote("bench-scraper", "harborkit", {
        name: "Harborkit",
        origin: "Los Angeles, CA",
        speed: "us",
        unitCost: 4.1,
        inboundShipping: 0.6,
        packaging: 0.35,
        shipDaysMin: 3,
        shipDaysMax: 5,
        rating: 4.6,
        reviews: 90,
        moq: 1,
        returnWindowDays: 30,
        note: "Fine backup. Shelf price is a dollar higher.",
      }),
      quote("bench-scraper", "paperlane", {
        name: "Paperlane Direct",
        origin: "Yiwu, China",
        speed: "import",
        unitCost: 0.9,
        inboundShipping: 1.4,
        packaging: 0.2,
        shipDaysMin: 16,
        shipDaysMax: 24,
        rating: 4.4,
        reviews: 1200,
        moq: 24,
        returnWindowDays: 7,
        note: "Thin steel. MOQ 24. Not a test order.",
      }),
    ],
  },
  {
    id: "lid-labels",
    sku: "LN-LBL-48",
    name: "Deli-container labels, set of 48",
    titleLead: "Deli container labels, 48",
    category: "Organization",
    lane: "kitchen",
    occasion: "a fridge that has to make sense on Thursday",
    material: "Waterproof film, printed to order",
    size: "48 labels, 2 × 1 in",
    colorway: "Kraft",
    swatch: "#c4a574",
    ceiling: 16,
    neededInDays: 8,
    box: "48 labels on one sheet. Containers are not included.",
    useLine: "Date the quart when it goes in. The label survives a wet lid.",
    colorNote: "Kraft ground, black type. Fields are item, date, and use-by. No logo lockup.",
    hook: "Date the quart. Future you is tired.",
    searchPhrase: "waterproof deli container labels fridge",
    keywords: ["fridge labels", "deli containers", "meal prep", "kitchen organization"],
    complements: "the quarts you already own",
    trend: {
      platform: "Posts",
      title: "Label the fridge like a walk-in",
      signal: "Home cooks who work service are posting labeled quarts, not aesthetic pantry shelves.",
      evidence:
        "photos of a home fridge labeled the way a walk-in is labeled. Print-on-demand in Ohio. No reason to boat a sticker.",
    },
    mockups: [
      {
        title: "On a lid",
        direction: "One label on a quart lid, filled in by hand: chili, date, use-by.",
        layout: "stack",
        src: "/art/mock-lid-labels-1.png",
      },
      {
        title: "The sheet",
        direction: "Full sheet of 48 so the count is the photo.",
        layout: "line",
        src: "/art/mock-lid-labels-2.png",
      },
      {
        title: "In the fridge",
        direction: "Three labeled lids on a shelf.",
        layout: "pair",
        src: "/art/mock-lid-labels-3.png",
      },
    ],
    suppliers: [
      quote("lid-labels", "pressroom", {
        name: "Pressroom",
        origin: "Columbus, OH",
        speed: "pod",
        unitCost: 2.8,
        inboundShipping: 0.9,
        packaging: 0.25,
        shipDaysMin: 2,
        shipDaysMax: 4,
        rating: 4.8,
        reviews: 520,
        moq: 1,
        returnWindowDays: 30,
        note: "Prints after the order. Waterproof film matched the sample in a sink test.",
      }),
      quote("lid-labels", "harborkit", {
        name: "Harborkit",
        origin: "Los Angeles, CA",
        speed: "us",
        unitCost: 3.6,
        inboundShipping: 0.7,
        packaging: 0.3,
        shipDaysMin: 3,
        shipDaysMax: 6,
        rating: 4.6,
        reviews: 70,
        moq: 1,
        returnWindowDays: 30,
        note: "Preprinted stock. Less flexible if you change the fields.",
      }),
      quote("lid-labels", "paperlane", {
        name: "Paperlane Direct",
        origin: "Yiwu, China",
        speed: "import",
        unitCost: 0.6,
        inboundShipping: 1.5,
        packaging: 0.15,
        shipDaysMin: 18,
        shipDaysMax: 26,
        rating: 4.3,
        reviews: 300,
        moq: 50,
        returnWindowDays: 7,
        note: "Paper, not film. They die on a wet lid.",
      }),
    ],
  },
  {
    id: "splatter",
    sku: "LN-SPL-13",
    name: "Fine-mesh splatter screen, 13 inch",
    titleLead: "Splatter screen, 13 in",
    category: "Safety",
    lane: "kitchen",
    occasion: "a pan that will spit",
    material: "Stainless mesh, folding handle",
    size: "13 in",
    colorway: "Steel",
    swatch: "#9aa0a6",
    ceiling: 22,
    neededInDays: 10,
    box: "One screen. The handle folds. No silicone rim.",
    useLine: "Set it on the skillet. Oil stays in the pan and off your forearm.",
    colorNote: "Fine mesh, not a glass lid. You can still see the fond.",
    hook: "The burn is optional. The screen is not.",
    searchPhrase: "splatter screen stainless skillet",
    keywords: ["splatter screen", "skillet", "kitchen safety", "frying"],
    complements: "the sheet pan and a real towel",
    trend: {
      platform: "TikTok",
      title: "Stop getting hit by the pan",
      signal: "Home-cook safety clips are a screen on a skillet, not a gag gift oven mitt.",
      evidence:
        "TikTok: bacon and chicken-thigh clips where the screen is the whole point. US mesh is in stock. The import version sheds wires.",
    },
    mockups: [
      {
        title: "On the skillet",
        direction: "Screen covering a skillet, handle folded out. No face in frame.",
        layout: "pair",
        src: "/art/mock-splatter-1.png",
      },
      {
        title: "Mesh",
        direction: "Crop on the mesh so buyers can see it is fine, not a colander.",
        layout: "stack",
        src: "/art/mock-splatter-2.png",
      },
      {
        title: "Beside the pan",
        direction: "Screen folded next to the skillet.",
        layout: "line",
        src: "/art/mock-splatter-3.png",
      },
    ],
    suppliers: [
      quote("splatter", "northwharf", {
        name: "Northwharf Goods",
        origin: "Elizabeth, NJ",
        speed: "us",
        unitCost: 5.5,
        inboundShipping: 0,
        packaging: 0.55,
        shipDaysMin: 2,
        shipDaysMax: 4,
        rating: 4.7,
        reviews: 280,
        moq: 1,
        returnWindowDays: 30,
        note: "Mesh is tight. Handle lock held on the sample.",
      }),
      quote("splatter", "harborkit", {
        name: "Harborkit",
        origin: "Los Angeles, CA",
        speed: "us",
        unitCost: 6.4,
        inboundShipping: 0.8,
        packaging: 0.5,
        shipDaysMin: 3,
        shipDaysMax: 5,
        rating: 4.6,
        reviews: 60,
        moq: 1,
        returnWindowDays: 30,
        note: "Same screen, slower only by a day from the coast.",
      }),
      quote("splatter", "paperlane", {
        name: "Paperlane Direct",
        origin: "Yiwu, China",
        speed: "import",
        unitCost: 1.8,
        inboundShipping: 2.2,
        packaging: 0.3,
        shipDaysMin: 16,
        shipDaysMax: 24,
        rating: 4.2,
        reviews: 740,
        moq: 12,
        returnWindowDays: 7,
        note: "Wires pull out. Do not put this over hot oil.",
      }),
    ],
  },
  {
    id: "shift-towel",
    sku: "LN-TWL-2",
    name: "Heavy kitchen towels, pair",
    titleLead: "Heavy kitchen towels, pair",
    category: "Linens",
    lane: "kitchen",
    occasion: "service at home",
    material: "Cotton terry, hemmed",
    size: "16 × 26 in, two towels",
    colorway: "Natural",
    swatch: "#e6e0d4",
    ceiling: 24,
    neededInDays: 12,
    box: "Two towels. No hanging loop, no embroidery.",
    useLine: "One on the handle, one on the shoulder. They are thick enough to pull a pan.",
    colorNote: "Undyed cotton. They stain. That is the job.",
    hook: "The towel is the tool. The decorative one stays in the drawer.",
    searchPhrase: "heavy cotton kitchen towels hot pans",
    keywords: ["kitchen towels", "side towel", "cotton towel", "line cook"],
    complements: "the sheet pan and the apron",
    trend: {
      platform: "Posts",
      title: "Side towels at home",
      signal: "The posts that land are a towel on the shoulder, not a matching set in a basket.",
      evidence:
        "From cooks who still work a line: the home kitchen fails when the towel is thin. US cotton, two-pack, no monogram.",
    },
    mockups: [
      {
        title: "Folded pair",
        direction: "Two towels stacked so the hem and the weight show.",
        layout: "stack",
        src: "/art/mock-shift-towel-1.png",
      },
      {
        title: "On a handle",
        direction: "One towel over an oven handle. No styled counter.",
        layout: "pair",
        src: "/art/mock-shift-towel-2.png",
      },
      {
        title: "In the drawer",
        direction: "A stack stored in an open drawer.",
        layout: "line",
        src: "/art/mock-shift-towel-3.png",
      },
    ],
    suppliers: [
      quote("shift-towel", "harborkit", {
        name: "Harborkit",
        origin: "Los Angeles, CA",
        speed: "us",
        unitCost: 6.2,
        inboundShipping: 0.8,
        packaging: 0.4,
        shipDaysMin: 3,
        shipDaysMax: 5,
        rating: 4.7,
        reviews: 150,
        moq: 1,
        returnWindowDays: 30,
        note: "Weight matched a restaurant side towel. Hem is double turned.",
      }),
      quote("shift-towel", "northwharf", {
        name: "Northwharf Goods",
        origin: "Elizabeth, NJ",
        speed: "us",
        unitCost: 6.8,
        inboundShipping: 0,
        packaging: 0.45,
        shipDaysMin: 2,
        shipDaysMax: 4,
        rating: 4.6,
        reviews: 80,
        moq: 1,
        returnWindowDays: 30,
        note: "Same cloth, East Coast, slightly higher unit.",
      }),
      quote("shift-towel", "paperlane", {
        name: "Paperlane Direct",
        origin: "Yiwu, China",
        speed: "import",
        unitCost: 2.1,
        inboundShipping: 2.4,
        packaging: 0.3,
        shipDaysMin: 18,
        shipDaysMax: 26,
        rating: 4.3,
        reviews: 400,
        moq: 20,
        returnWindowDays: 7,
        note: "Thin. You will feel the handle through it.",
      }),
    ],
  },
  {
    id: "apron",
    sku: "LN-APR-1",
    name: "Waist apron, unbleached canvas",
    titleLead: "Unbleached canvas waist apron",
    category: "Clothes",
    lane: "apparel",
    occasion: "a shift at home",
    material: "Cotton canvas, printed to order",
    size: "Waist, two pockets",
    colorway: "Natural",
    swatch: "#d7c4a3",
    ceiling: 32,
    neededInDays: 8,
    box: "One apron. Ties are cotton. No chest print.",
    useLine: "Tie it on for the hour you actually cook. Pockets hold a pen and a towel corner.",
    colorNote: "Undyed canvas. A small neck-side mark only, nothing across the bib, because there is no bib.",
    hook: "The apron is for the hour you cook, not for a slogan.",
    searchPhrase: "canvas waist apron no logo kitchen",
    keywords: ["waist apron", "canvas apron", "kitchen clothes", "line cook"],
    complements: "the towels and the sheet pan",
    trend: {
      platform: "Posts",
      title: "Clothes that survive a pan",
      signal: "Apparel that is moving with cooks is a plain waist apron, not a graphic tee about cooking.",
      evidence:
        "cooks posting what they wear at home after service. Plain canvas, two pockets. Print-on-demand in Ohio so a post on Tuesday can ship this week.",
    },
    mockups: [
      {
        title: "Tied",
        direction: "Waist only, pockets visible, no face required. Natural light.",
        layout: "pair",
        src: "/art/mock-apron-1.png",
      },
      {
        title: "Pocket",
        direction: "Crop on the pocket and the canvas weave.",
        layout: "stack",
        src: "/art/mock-apron-2.png",
      },
      {
        title: "On the hook",
        direction: "Hanging, pockets out.",
        layout: "line",
        src: "/art/mock-apron-3.png",
      },
    ],
    suppliers: [
      quote("apron", "pressroom", {
        name: "Pressroom",
        origin: "Columbus, OH",
        speed: "pod",
        unitCost: 8.5,
        inboundShipping: 1.4,
        packaging: 0.4,
        shipDaysMin: 3,
        shipDaysMax: 5,
        rating: 4.8,
        reviews: 860,
        moq: 1,
        returnWindowDays: 30,
        note: "Prints the small mark after checkout. Canvas weight is 10 oz on the spec.",
      }),
      quote("apron", "northwharf", {
        name: "Northwharf Goods",
        origin: "Elizabeth, NJ",
        speed: "us",
        unitCost: 11.2,
        inboundShipping: 0,
        packaging: 0.5,
        shipDaysMin: 2,
        shipDaysMax: 4,
        rating: 4.6,
        reviews: 40,
        moq: 1,
        returnWindowDays: 30,
        note: "Blank stock, no mark. Fine if you do not want print.",
      }),
      quote("apron", "paperlane", {
        name: "Paperlane Direct",
        origin: "Yiwu, China",
        speed: "import",
        unitCost: 3.4,
        inboundShipping: 3.1,
        packaging: 0.35,
        shipDaysMin: 18,
        shipDaysMax: 26,
        rating: 4.4,
        reviews: 500,
        moq: 20,
        returnWindowDays: 7,
        note: "Poly blend. It melts near a burner. Do not buy it.",
      }),
    ],
  },
  {
    id: "fish-spatula",
    sku: "LN-FSH-1",
    name: "Slotted stainless fish spatula",
    titleLead: "Slotted fish spatula",
    category: "Utensils",
    lane: "food",
    occasion: "the delicate flip",
    material: "Stainless steel",
    size: "12 in overall",
    colorway: "Steel",
    swatch: "#cfd2d6",
    ceiling: 22,
    neededInDays: 10,
    box: "One spatula. No nylon head, no hanging card.",
    useLine: "Slide it under a fillet or a fried egg. The slots let the fat drain.",
    colorNote: "One piece of steel, thin at the tip, not a coated turner.",
    hook: "If it flexes, it is the wrong spatula.",
    searchPhrase: "stainless slotted fish spatula",
    keywords: ["fish spatula", "slotted turner", "stainless utensil", "eggs"],
    complements: "the splatter screen and a real skillet",
    trend: {
      platform: "TikTok",
      title: "One spatula, not a crock of them",
      signal: "Utensil videos that hold are a single steel fish spatula. The 40-piece holders are the punchline.",
      evidence:
        "TikTok utensil audits keep one tool: a slotted fish spatula. US stainless is in Elizabeth. The coated import peels.",
    },
    mockups: [
      {
        title: "The tip",
        direction: "Tip of the spatula under the edge of an egg. Tight crop.",
        layout: "stack",
        src: "/art/mock-fish-spatula-1.png",
      },
      {
        title: "Full tool",
        direction: "Whole spatula on a board, slots visible.",
        layout: "line",
        src: "/art/mock-fish-spatula-2.png",
      },
      {
        title: "In the drawer",
        direction: "Resting with one other utensil.",
        layout: "pair",
        src: "/art/mock-fish-spatula-3.png",
      },
    ],
    suppliers: [
      quote("fish-spatula", "northwharf", {
        name: "Northwharf Goods",
        origin: "Elizabeth, NJ",
        speed: "us",
        unitCost: 5.2,
        inboundShipping: 0,
        packaging: 0.4,
        shipDaysMin: 2,
        shipDaysMax: 4,
        rating: 4.8,
        reviews: 330,
        moq: 1,
        returnWindowDays: 30,
        note: "Flex is right. Tip did not bend on the sample fillet.",
      }),
      quote("fish-spatula", "harborkit", {
        name: "Harborkit",
        origin: "Los Angeles, CA",
        speed: "us",
        unitCost: 6.1,
        inboundShipping: 0.7,
        packaging: 0.4,
        shipDaysMin: 3,
        shipDaysMax: 5,
        rating: 4.6,
        reviews: 55,
        moq: 1,
        returnWindowDays: 30,
        note: "Same tool, higher freight from LA.",
      }),
      quote("fish-spatula", "paperlane", {
        name: "Paperlane Direct",
        origin: "Yiwu, China",
        speed: "import",
        unitCost: 1.5,
        inboundShipping: 1.8,
        packaging: 0.25,
        shipDaysMin: 16,
        shipDaysMax: 24,
        rating: 4.3,
        reviews: 880,
        moq: 20,
        returnWindowDays: 7,
        note: "Coating flakes into the pan. Pass.",
      }),
    ],
  },
  {
    id: "tongs",
    sku: "LN-TNG-12",
    name: "Locking stainless tongs, 12 inch",
    titleLead: "Locking tongs, 12 in",
    category: "Utensils",
    lane: "kitchen",
    occasion: "the pan and the grill",
    material: "Stainless steel",
    size: "12 in",
    colorway: "Steel",
    swatch: "#b7bcc2",
    ceiling: 20,
    neededInDays: 10,
    box: "One pair. Locking ring works one-handed. No silicone tips.",
    useLine: "Turn meat, pull a sheet pan, plate without a second tool.",
    colorNote: "Scalloped tips, bare steel. Silicone tips melt and hide the sear.",
    hook: "Twelve inches. Locking. No silicone.",
    searchPhrase: "12 inch locking stainless tongs",
    keywords: ["kitchen tongs", "locking tongs", "stainless tongs", "grill tongs"],
    complements: "the fish spatula and the sheet pan",
    trend: {
      platform: "Posts",
      title: "The tong test",
      signal: "Cooks are arguing about tongs again, and the answer that repeats is 12-inch steel with a lock.",
      evidence:
        "silicone tips versus steel. The posts that get saved specify a lock and 12 inches. That SKU is in New Jersey.",
    },
    mockups: [
      {
        title: "Locked",
        direction: "Tongs closed and locked, full length in frame.",
        layout: "line",
        src: "/art/mock-tongs-1.png",
      },
      {
        title: "Tips",
        direction: "Crop on the scalloped tips so buyers see there is no silicone.",
        layout: "stack",
        src: "/art/mock-tongs-2.png",
      },
      {
        title: "On the rail",
        direction: "Hanging full length.",
        layout: "pair",
        src: "/art/mock-tongs-3.png",
      },
    ],
    suppliers: [
      quote("tongs", "northwharf", {
        name: "Northwharf Goods",
        origin: "Elizabeth, NJ",
        speed: "us",
        unitCost: 4.8,
        inboundShipping: 0,
        packaging: 0.45,
        shipDaysMin: 2,
        shipDaysMax: 4,
        rating: 4.8,
        reviews: 510,
        moq: 1,
        returnWindowDays: 30,
        note: "Spring is not brutal. Lock engages. Sample passed.",
      }),
      quote("tongs", "harborkit", {
        name: "Harborkit",
        origin: "Los Angeles, CA",
        speed: "us",
        unitCost: 5.6,
        inboundShipping: 0.7,
        packaging: 0.4,
        shipDaysMin: 3,
        shipDaysMax: 5,
        rating: 4.7,
        reviews: 120,
        moq: 1,
        returnWindowDays: 30,
        note: "West Coast pair. Slightly dearer.",
      }),
      quote("tongs", "paperlane", {
        name: "Paperlane Direct",
        origin: "Yiwu, China",
        speed: "import",
        unitCost: 1.4,
        inboundShipping: 1.9,
        packaging: 0.25,
        shipDaysMin: 16,
        shipDaysMax: 24,
        rating: 4.4,
        reviews: 1500,
        moq: 24,
        returnWindowDays: 7,
        note: "Silicone tips and a weak lock. The viral complaint.",
      }),
    ],
  },
  {
    id: "garlic-press",
    sku: "LN-GAR-1",
    name: "Viral garlic press",
    titleLead: "Garlic press",
    category: "Gadgets",
    lane: "food",
    occasion: "a clip, not a kitchen",
    material: "Zinc alloy",
    size: "One press",
    colorway: "Black",
    swatch: "#2a2a2a",
    ceiling: 18,
    neededInDays: 7,
    box: "One press and a cleaning pick.",
    useLine: "It is the tool in the clip. A knife still does the job faster.",
    colorNote: "Black handles. The chamber clogs. Say so if you ever revive it.",
    hook: "The clip is viral. The press is not the buy.",
    searchPhrase: "garlic press viral kitchen gadget",
    keywords: ["garlic press", "kitchen gadget", "viral"],
    complements: "nothing you would put next to a real prep kit",
    trend: {
      platform: "TikTok",
      title: "Garlic press, again",
      signal: "The views are real. The fast quote cannot hold a price anyone will pay.",
      evidence:
        "TikTok views on the press are high this week. US landed cost blows the $18 ceiling. The cheap quote is a three-week boat. Pass.",
    },
    mockups: [
      {
        title: "The press",
        direction: "Product on white. Do not shoot it mid-crush unless you are reviving the SKU.",
        layout: "stack",
        src: "/art/mock-garlic-press-1.png",
      },
      {
        title: "Clog",
        direction: "If you shoot it, show the chamber so the con is visible.",
        layout: "pair",
        src: "/art/mock-garlic-press-2.png",
      },
      {
        title: "Next to one clove",
        direction: "The press beside a single clove.",
        layout: "line",
        src: "/art/mock-garlic-press-3.png",
      },
    ],
    suppliers: [
      quote("garlic-press", "northwharf", {
        name: "Northwharf Goods",
        origin: "Elizabeth, NJ",
        speed: "us",
        unitCost: 11.2,
        inboundShipping: 0,
        packaging: 0.5,
        shipDaysMin: 2,
        shipDaysMax: 4,
        rating: 4.6,
        reviews: 40,
        moq: 1,
        returnWindowDays: 30,
        note: "In stock, and the shelf price to hold margin is over the comp.",
      }),
      quote("garlic-press", "harborkit", {
        name: "Harborkit",
        origin: "Los Angeles, CA",
        speed: "us",
        unitCost: 12.4,
        inboundShipping: 0.8,
        packaging: 0.45,
        shipDaysMin: 3,
        shipDaysMax: 5,
        rating: 4.5,
        reviews: 22,
        moq: 1,
        returnWindowDays: 30,
        note: "Same problem, higher cost.",
      }),
      quote("garlic-press", "paperlane", {
        name: "Paperlane Direct",
        origin: "Yiwu, China",
        speed: "import",
        unitCost: 1.6,
        inboundShipping: 1.7,
        packaging: 0.25,
        shipDaysMin: 16,
        shipDaysMax: 24,
        rating: 4.2,
        reviews: 2200,
        moq: 30,
        returnWindowDays: 7,
        note: "The AliExpress price. Three weeks, and the hinge fails.",
      }),
    ],
  },
  {
    id: "court-towel",
    sku: "LN-CRT-1",
    name: "Court towel, microfiber",
    titleLead: "Court towel",
    category: "Sports",
    lane: "sport",
    occasion: "between points",
    material: "Microfiber",
    size: "16 × 28 in",
    colorway: "Court green",
    swatch: "#3d7a4a",
    ceiling: 18,
    neededInDays: 14,
    box: "One towel. No slogan, no player name.",
    useLine: "Clip it on the fence or the bag. It is for sweat and a grip, not a beach.",
    colorNote: "Court green. A small woven label, nothing printed across the field.",
    hook: "The towel on the fence is the product. The slogan shirt is not.",
    searchPhrase: "pickleball court towel microfiber",
    keywords: ["court towel", "pickleball", "sports towel", "microfiber"],
    complements: "a paddle you already own",
    trend: {
      platform: "Posts",
      title: "Court towels, not more paddles",
      signal: "Adult rec sports posts show the towel on the fence more often than another paddle.",
      evidence:
        "Rec-sports clips: a plain towel on the fence. US microfiber, no joke print, ships this week.",
    },
    mockups: [
      {
        title: "On a fence",
        direction: "Towel over a chain fence, paddle out of focus.",
        layout: "line",
        src: "/art/mock-court-towel-1.png",
      },
      {
        title: "Fold",
        direction: "Folded towel, no text across the cloth.",
        layout: "stack",
        src: "/art/mock-court-towel-2.png",
      },
      {
        title: "On the bench",
        direction: "Folded towel courtside. No words on the cloth.",
        layout: "pair",
        src: "/art/mock-court-towel-3.png",
      },
    ],
    suppliers: [
      quote("court-towel", "harborkit", {
        name: "Harborkit",
        origin: "Los Angeles, CA",
        speed: "us",
        unitCost: 3.8,
        inboundShipping: 0.6,
        packaging: 0.3,
        shipDaysMin: 2,
        shipDaysMax: 4,
        rating: 4.7,
        reviews: 190,
        moq: 1,
        returnWindowDays: 30,
        note: "GSM is heavy enough to matter. Label is woven.",
      }),
      quote("court-towel", "northwharf", {
        name: "Northwharf Goods",
        origin: "Elizabeth, NJ",
        speed: "us",
        unitCost: 4.2,
        inboundShipping: 0,
        packaging: 0.35,
        shipDaysMin: 2,
        shipDaysMax: 4,
        rating: 4.6,
        reviews: 60,
        moq: 1,
        returnWindowDays: 30,
        note: "East Coast. A bit more money.",
      }),
      quote("court-towel", "paperlane", {
        name: "Paperlane Direct",
        origin: "Yiwu, China",
        speed: "import",
        unitCost: 1.1,
        inboundShipping: 1.6,
        packaging: 0.2,
        shipDaysMin: 16,
        shipDaysMax: 24,
        rating: 4.4,
        reviews: 700,
        moq: 30,
        returnWindowDays: 7,
        note: "Printed slogans and thin cloth. Skip.",
      }),
    ],
  },
  {
    id: "cord-clips",
    sku: "LN-CRD-20",
    name: "Adhesive cord clips, set of 20",
    titleLead: "Cord clips, set of 20",
    category: "Utility",
    lane: "utility",
    occasion: "a counter with one too many cords",
    material: "Plastic clip, acrylic adhesive",
    size: "20 clips",
    colorway: "White",
    swatch: "#f4f4f2",
    ceiling: 14,
    neededInDays: 14,
    box: "20 clips. No cable sleeves, no zip ties.",
    useLine: "Run the charger cord along the back of the counter. One job.",
    colorNote: "White. They disappear on a light wall and show on a dark one. Say that.",
    hook: "The cord is the mess. Twenty clips is the fix.",
    searchPhrase: "adhesive cord clips kitchen counter",
    keywords: ["cord clips", "cable management", "desk organization", "utility"],
    complements: "the label maker energy, not another bin",
    trend: {
      platform: "TikTok",
      title: "Cord clips under the cabinet",
      signal: "Utility clips are outrunning the acrylic organizer bins in home-setup videos.",
      evidence:
        "TikTok desk and kitchen resets: adhesive clips along a cabinet lip. US pack of 20. Not a 200-piece import kit.",
    },
    mockups: [
      {
        title: "Under the lip",
        direction: "Three clips holding one white cord under a counter edge.",
        layout: "line",
        src: "/art/mock-cord-clips-1.png",
      },
      {
        title: "The twenty",
        direction: "All 20 on the backing card so the count is obvious.",
        layout: "stack",
        src: "/art/mock-cord-clips-2.png",
      },
      {
        title: "Along the desk",
        direction: "Clips holding one cable at the back edge.",
        layout: "pair",
        src: "/art/mock-cord-clips-3.png",
      },
    ],
    suppliers: [
      quote("cord-clips", "northwharf", {
        name: "Northwharf Goods",
        origin: "Elizabeth, NJ",
        speed: "us",
        unitCost: 2.6,
        inboundShipping: 0,
        packaging: 0.25,
        shipDaysMin: 2,
        shipDaysMax: 4,
        rating: 4.7,
        reviews: 260,
        moq: 1,
        returnWindowDays: 30,
        note: "Adhesive held on painted wood in the sample. Not on brick.",
      }),
      quote("cord-clips", "harborkit", {
        name: "Harborkit",
        origin: "Los Angeles, CA",
        speed: "us",
        unitCost: 3.1,
        inboundShipping: 0.5,
        packaging: 0.25,
        shipDaysMin: 3,
        shipDaysMax: 5,
        rating: 4.6,
        reviews: 80,
        moq: 1,
        returnWindowDays: 30,
        note: "Same clip. Use if NJ sells through.",
      }),
      quote("cord-clips", "paperlane", {
        name: "Paperlane Direct",
        origin: "Yiwu, China",
        speed: "import",
        unitCost: 0.4,
        inboundShipping: 1.3,
        packaging: 0.15,
        shipDaysMin: 18,
        shipDaysMax: 26,
        rating: 4.3,
        reviews: 2000,
        moq: 50,
        returnWindowDays: 7,
        note: "Adhesive lets go in a week. The reviews are the product.",
      }),
    ],
  },
  {
    id: "citrus-press",
    sku: "LN-CIT-1",
    name: "Handheld citrus press",
    titleLead: "Handheld citrus press",
    category: "Utensils",
    lane: "food",
    occasion: "a pan sauce",
    material: "Stainless steel",
    size: "Fits a lemon or a lime",
    colorway: "Steel",
    swatch: "#d5d8dd",
    ceiling: 24,
    neededInDays: 12,
    box: "One press. No reamer, no pitcher.",
    useLine: "Half a lemon over a finished pan. Seeds stay in the press.",
    colorNote: "Steel, not painted. Acid will mark it. That is fine.",
    hook: "Seeds stay in the press. The juice hits the pan.",
    searchPhrase: "stainless handheld lemon press",
    keywords: ["citrus press", "lemon squeezer", "kitchen utensil", "pan sauce"],
    complements: "the fish spatula and a skillet",
    trend: {
      platform: "Instagram",
      title: "The lemon at the end",
      signal: "Finish-the-dish clips end on a handheld press, not a countertop juicer.",
      evidence:
        "Instagram cooking clips close on a lemon over the pan. A handheld steel press from US stock. Skip the electric juicer.",
    },
    mockups: [
      {
        title: "Over the pan",
        direction: "Press in hand above a skillet, one lemon half. Hands only.",
        layout: "pair",
        src: "/art/mock-citrus-press-1.png",
      },
      {
        title: "Open",
        direction: "Press open so the cup and the hinge are clear.",
        layout: "stack",
        src: "/art/mock-citrus-press-2.png",
      },
      {
        title: "Closed",
        direction: "The press shut on a board. No fruit pile.",
        layout: "line",
        src: "/art/mock-citrus-press-3.png",
      },
    ],
    suppliers: [
      quote("citrus-press", "northwharf", {
        name: "Northwharf Goods",
        origin: "Elizabeth, NJ",
        speed: "us",
        unitCost: 6.4,
        inboundShipping: 0,
        packaging: 0.45,
        shipDaysMin: 2,
        shipDaysMax: 4,
        rating: 4.8,
        reviews: 240,
        moq: 1,
        returnWindowDays: 30,
        note: "Hinge is tight. A lemon half fits. A grapefruit does not. Say that.",
      }),
      quote("citrus-press", "harborkit", {
        name: "Harborkit",
        origin: "Los Angeles, CA",
        speed: "us",
        unitCost: 7.2,
        inboundShipping: 0.7,
        packaging: 0.4,
        shipDaysMin: 3,
        shipDaysMax: 5,
        rating: 4.6,
        reviews: 50,
        moq: 1,
        returnWindowDays: 30,
        note: "Backup stock.",
      }),
      quote("citrus-press", "paperlane", {
        name: "Paperlane Direct",
        origin: "Yiwu, China",
        speed: "import",
        unitCost: 2.2,
        inboundShipping: 1.9,
        packaging: 0.3,
        shipDaysMin: 16,
        shipDaysMax: 24,
        rating: 4.4,
        reviews: 640,
        moq: 12,
        returnWindowDays: 7,
        note: "Painted alloy. The finish comes off in the dishwasher.",
      }),
    ],
  },
  {
    id: "favor-boxes",
    sku: "LN-BOX-12",
    name: "Plain rigid favor boxes, set of 12",
    titleLead: "Plain favor boxes, 12",
    category: "Party extra",
    lane: "party-extra",
    occasion: "the thing guests carry out",
    material: "Paperboard",
    size: "3 in cube, 12 boxes",
    colorway: "White",
    swatch: "#f7f7f6",
    ceiling: 16,
    neededInDays: 14,
    box: "12 white boxes, flat-packed, with lids. No tissue, no sticker, no name.",
    useLine: "The handmade thing on the table stays on the table. This is the box it leaves in.",
    colorNote: "Plain white. No print, so it does not compete with a custom invitation or a handmade favor.",
    hook: "Not the centerpiece. The box the centerpiece leaves in.",
    searchPhrase: "plain white favor boxes no print",
    keywords: ["favor boxes", "party boxes", "white box", "event extra"],
    complements: "someone else's handmade table, not a second decor shop",
    trend: {
      platform: "Instagram",
      title: "The carry-home, not the tablescape",
      signal: "Event posts show a plain box next to a handmade favor. The box is the gap. The handmade piece is not ours.",
      evidence:
        "Instagram event saves: a custom cookie or a small candle in a plain white box. We sell the box. We do not sell the candle, the bow, or the sign.",
    },
    mockups: [
      {
        title: "Twelve",
        direction: "Twelve closed white boxes in a grid. No ribbon.",
        layout: "line",
        src: "/art/mock-favor-boxes-1.png",
      },
      {
        title: "One open",
        direction: "One box open and empty, so it is obvious we are not selling what goes inside.",
        layout: "stack",
        src: "/art/mock-favor-boxes-2.png",
      },
      {
        title: "Set out",
        direction: "One plain box on a table. No ribbon.",
        layout: "pair",
        src: "/art/mock-favor-boxes-3.png",
      },
    ],
    suppliers: [
      quote("favor-boxes", "harborkit", {
        name: "Harborkit",
        origin: "Los Angeles, CA",
        speed: "us",
        unitCost: 3.5,
        inboundShipping: 0.8,
        packaging: 0.3,
        shipDaysMin: 3,
        shipDaysMax: 5,
        rating: 4.7,
        reviews: 140,
        moq: 1,
        returnWindowDays: 30,
        note: "Rigid enough to hold a cookie. No print. Lands before a two-week event.",
      }),
      quote("favor-boxes", "pressroom", {
        name: "Pressroom",
        origin: "Columbus, OH",
        speed: "pod",
        unitCost: 4.4,
        inboundShipping: 0.9,
        packaging: 0.3,
        shipDaysMin: 3,
        shipDaysMax: 6,
        rating: 4.6,
        reviews: 60,
        moq: 1,
        returnWindowDays: 30,
        note: "Can add a name later. Do not. A name starts copying the handmade lane.",
      }),
      quote("favor-boxes", "paperlane", {
        name: "Paperlane Direct",
        origin: "Yiwu, China",
        speed: "import",
        unitCost: 1.2,
        inboundShipping: 2.2,
        packaging: 0.25,
        shipDaysMin: 18,
        shipDaysMax: 26,
        rating: 4.4,
        reviews: 500,
        moq: 24,
        returnWindowDays: 7,
        note: "Printed florals. That is the thing we are not selling.",
      }),
    ],
  },
  {
    id: "heavy-tee",
    sku: "LN-TEE-1",
    name: "Heavyweight tee, ink navy",
    titleLead: "Heavyweight tee, ink navy",
    category: "Clothes",
    lane: "apparel",
    occasion: "the shirt under the apron",
    material: "Cotton jersey, printed to order",
    size: "S–XL, listed per size",
    colorway: "Ink navy",
    swatch: "#1f3a5f",
    ceiling: 36,
    neededInDays: 8,
    box: "One shirt. No front graphic. A small mark at the hem.",
    useLine: "Wear it under the apron or on the way in. The weight is the point, not a joke on the chest.",
    colorNote: "Ink navy, not royal. The fabric is 6.5 oz. Say the ounces.",
    hook: "Heavy shirt. No sentence on the front.",
    searchPhrase: "heavyweight blank tee navy",
    keywords: ["heavyweight tee", "blank tee", "navy shirt", "cotton tee"],
    complements: "the waist apron, not a graphic drop",
    trend: {
      platform: "Posts",
      title: "Heavy blanks, not slogan shirts",
      signal: "The apparel posts that keep moving are a heavy blank in a serious color, photographed flat.",
      evidence:
        "Apparel posts this month: heavyweight navy, no chest hit. Print-on-demand in Ohio so a post does not wait on a container.",
    },
    mockups: [
      {
        title: "Flat",
        direction: "Shirt flat on a table, hem mark visible, no model required.",
        layout: "stack",
        src: "/art/mock-heavy-tee-1.png",
      },
      {
        title: "Weight",
        direction: "Crop on the collar and the jersey so the weight reads.",
        layout: "pair",
        src: "/art/mock-heavy-tee-2.png",
      },
      {
        title: "On a hanger",
        direction: "Blank navy shirt, no model, no slogan.",
        layout: "line",
        src: "/art/mock-heavy-tee-3.png",
      },
    ],
    suppliers: [
      quote("heavy-tee", "pressroom", {
        name: "Pressroom",
        origin: "Columbus, OH",
        speed: "pod",
        unitCost: 9.8,
        inboundShipping: 1.6,
        packaging: 0.4,
        shipDaysMin: 3,
        shipDaysMax: 6,
        rating: 4.8,
        reviews: 1100,
        moq: 1,
        returnWindowDays: 30,
        note: "Prints the hem mark after the order. Size run is real. Do not promise a fit you have not worn.",
      }),
      quote("heavy-tee", "northwharf", {
        name: "Northwharf Goods",
        origin: "Elizabeth, NJ",
        speed: "us",
        unitCost: 12.5,
        inboundShipping: 0,
        packaging: 0.45,
        shipDaysMin: 2,
        shipDaysMax: 4,
        rating: 4.6,
        reviews: 30,
        moq: 1,
        returnWindowDays: 30,
        note: "Blank, no hem mark. Faster, and you hold the size.",
      }),
      quote("heavy-tee", "paperlane", {
        name: "Paperlane Direct",
        origin: "Yiwu, China",
        speed: "import",
        unitCost: 3.2,
        inboundShipping: 3.4,
        packaging: 0.3,
        shipDaysMin: 18,
        shipDaysMax: 28,
        rating: 4.3,
        reviews: 900,
        moq: 50,
        returnWindowDays: 7,
        note: "Light jersey and a chest slogan. That is the opposite of the post.",
      }),
    ],
  },
];

export const products: Product[] = [...catalogProducts, ...stocked];

const remembered = new Map<string, Product>();

export function rememberProduct(product: Product) {
  remembered.set(product.id, product);
}

export function findProduct(id: string) {
  return products.find((item) => item.id === id) ?? remembered.get(id);
}

export function getProduct(id: string) {
  const product = findProduct(id);
  if (!product) throw new Error(`Unknown product ${id}`);
  return product;
}
